name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Dharaneesh20
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
